"""add admin sessions and login attempts

Revision ID: 0c344a4221d7
Revises: a9369e2dec1b
Create Date: 2026-08-18 06:33:58.038932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0c344a4221d7'
down_revision: Union[str, None] = 'a9369e2dec1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ip_hash', sa.Text(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_login_attempts_ip_created', 'login_attempts', ['ip_hash', 'created_at'], unique=False)
    op.create_table('admin_sessions',
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['admin_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_sessions')
    op.drop_index('idx_login_attempts_ip_created', table_name='login_attempts')
    op.drop_table('login_attempts')
    # ### end Alembic commands ###
