"""add certifications

Revision ID: 854d18a45c4e
Revises: 0c344a4221d7
Create Date: 2026-08-18 07:33:44.371007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '854d18a45c4e'
down_revision: Union[str, None] = '0c344a4221d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('issuer', sa.Text(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('credential_url', sa.Text(), nullable=True),
    sa.Column('badge_image_url', sa.Text(), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_certifications_featured', 'certifications', ['featured'], unique=False)
    op.create_index('idx_certifications_sort_order', 'certifications', ['sort_order'], unique=False)
    op.create_table('certification_translations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('certification_id', sa.UUID(), nullable=False),
    sa.Column(
        'locale',
        postgresql.ENUM('en', 'es', name='locale_type', create_type=False),
        nullable=False,
    ),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['certification_id'], ['certifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('certification_id', 'locale', name='uq_certification_locale')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('certification_translations')
    op.drop_index('idx_certifications_sort_order', table_name='certifications')
    op.drop_index('idx_certifications_featured', table_name='certifications')
    op.drop_table('certifications')
    # ### end Alembic commands ###
