"""initial schema

Revision ID: a9369e2dec1b
Revises: 
Create Date: 2026-08-18 05:48:10.251492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a9369e2dec1b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('featured', 'software', 'embedded', 'electronics', 'robotics', 'ml_data', 'cybersecurity', 'devops_infra', 'academic_research', name='project_category'), nullable=False),
    sa.Column('github_url', sa.Text(), nullable=True),
    sa.Column('demo_url', sa.Text(), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_projects_category', 'projects', ['category'], unique=False)
    op.create_index('idx_projects_featured', 'projects', ['featured'], unique=False, postgresql_where=sa.text('featured = true'))
    op.create_index('idx_projects_sort_order', 'projects', ['sort_order'], unique=False)
    op.create_table('skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('programming', 'embedded_systems', 'electronics', 'automation', 'web_dev', 'ml_data', 'cybersecurity', 'linux_devops', 'engineering_tools', name='skill_category'), nullable=False),
    sa.Column('proficiency', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('icon_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_skills_category', 'skills', ['category'], unique=False)
    op.create_table('technologies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('programming', 'embedded_systems', 'electronics', 'automation', 'web_dev', 'ml_data', 'cybersecurity', 'linux_devops', 'engineering_tools', name='tech_category'), nullable=False),
    sa.Column('icon_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_technologies_category', 'technologies', ['category'], unique=False)
    op.create_table('analytics_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.Enum('page_view', 'project_view', 'project_link_click', 'github_click', 'cv_download', 'contact_click', 'language_change', name='analytics_event_type'), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('project_slug', sa.Text(), nullable=True),
    sa.Column('locale', sa.Enum('en', 'es', name='locale_type'), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_agent_hash', sa.Text(), nullable=True),
    sa.Column('ip_hash', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_analytics_created_at', 'analytics_events', ['created_at'], unique=False)
    op.create_index('idx_analytics_event_type', 'analytics_events', ['event_type'], unique=False)
    op.create_index('idx_analytics_project_id', 'analytics_events', ['project_id'], unique=False)
    op.create_index('idx_analytics_session', 'analytics_events', ['session_id'], unique=False)
    op.create_table('project_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('alt_text', sa.Text(), nullable=True),
    sa.Column('is_hero', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_technologies',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('technology_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'technology_id')
    )
    op.create_table('project_translations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('locale', sa.Enum('en', 'es', name='locale_type'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('short_desc', sa.Text(), nullable=False),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('problem', sa.Text(), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('architecture', sa.Text(), nullable=True),
    sa.Column('implementation', sa.Text(), nullable=True),
    sa.Column('decisions', sa.Text(), nullable=True),
    sa.Column('challenges', sa.Text(), nullable=True),
    sa.Column('testing_desc', sa.Text(), nullable=True),
    sa.Column('results', sa.Text(), nullable=True),
    sa.Column('lessons', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'locale', name='uq_project_locale')
    )
    op.create_index('idx_pt_locale', 'project_translations', ['locale'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_pt_locale', table_name='project_translations')
    op.drop_table('project_translations')
    op.drop_table('project_technologies')
    op.drop_table('project_images')
    op.drop_index('idx_analytics_session', table_name='analytics_events')
    op.drop_index('idx_analytics_project_id', table_name='analytics_events')
    op.drop_index('idx_analytics_event_type', table_name='analytics_events')
    op.drop_index('idx_analytics_created_at', table_name='analytics_events')
    op.drop_table('analytics_events')
    op.drop_index('idx_technologies_category', table_name='technologies')
    op.drop_table('technologies')
    op.drop_index('idx_skills_category', table_name='skills')
    op.drop_table('skills')
    op.drop_index('idx_projects_sort_order', table_name='projects')
    op.drop_index('idx_projects_featured', table_name='projects', postgresql_where=sa.text('featured = true'))
    op.drop_index('idx_projects_category', table_name='projects')
    op.drop_table('projects')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
    sa.Enum(name='project_category').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='skill_category').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='tech_category').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='analytics_event_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='locale_type').drop(op.get_bind(), checkfirst=True)
