"""add network health samples

Revision ID: bf0d8d836407
Revises: 854d18a45c4e
Create Date: 2026-08-19 05:56:34.871212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'bf0d8d836407'
down_revision: Union[str, None] = '854d18a45c4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network_health_samples',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sampled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('services', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('internet_targets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('packet_loss_pct', sa.Float(), nullable=True),
    sa.Column('cpu_percent', sa.Float(), nullable=True),
    sa.Column('memory_percent', sa.Float(), nullable=True),
    sa.Column('disk_percent', sa.Float(), nullable=True),
    sa.Column('requests_count', sa.Integer(), nullable=True),
    sa.Column('errors_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_nhs_sampled_at', 'network_health_samples', ['sampled_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_nhs_sampled_at', table_name='network_health_samples')
    op.drop_table('network_health_samples')
    # ### end Alembic commands ###
